version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  fastapi_app:
    build: .
    container_name: fastapi_app
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://root:example@mongo:27017/?authSource=admin
